// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int N = Integer.parseInt(args[0]);
		int biger = 0;
		int smaller = 0;
		for (int i = 0 ; i < N ; i++){
			double random =  Math.random();
			if (random>0.5) {
				biger++;
			}
			else{
				smaller++;
			}
		}  

		System.out.println(">0.5: " + biger);
		System.out.println("<=0.5: " + smaller);

		if(biger == 0 || smaller == 0){
		}else{
			double ratio =  biger/smaller;
			System.out.println("Ratio: " + ratio );
		}
}
}
